version: '3.8'
services:
  # Config servers
  config1:
    image: mongo:8.0
    container_name: config1
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27023", "--bind_ip_all"]
    ports: ["27023:27023"]
    volumes:
      - ./data/configsvr:/data/db

  # Shard 1
  shard1_1:
    image: mongo:8.0
    container_name: shard1_1
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27021", "--bind_ip_all"]
    ports: ["27021:27021"]
    volumes:
      - ./data/shard1:/data/db

  # Shard 2
  shard2_1:
    image: mongo:8.0
    container_name: shard2_1
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27022", "--bind_ip_all"]
    ports: ["27022:27022"]
    volumes:
      - ./data/shard2:/data/db

  # Mongos router
  mongos:
    image: mongo:8.0
    container_name: mongos
    command: >
      mongos --configdb cfgRS/config1:27019 --bind_ip_all --port 27020
    ports: ["27020:27020"]
